services:
  strava-stats:
    image: robiningelbrecht/strava-statistics:latest
    container_name: strava-stats
    volumes:
      - strava-stats_build:/var/www/build/:rw
      - strava-stats_db:/var/www/storage/database:rw
      - strava-stats_logs:/var/www/storage/files:rw # HTML, logs, etc.
      - /self-hosted/strava-stats/.env:/var/www/.env:ro
    env_file: .env
    # expose:
    #   - 8080
    ports:
      - 8070:8080/tcp
    #user: ${PUID}:${PGID}
    restart: unless-stopped
    networks:
      - proxy-net
networks:
  strava-net:
    name: strava-net
  proxy-net:
    external: true
volumes:
  strava-stats_build:
    name: strava-stats_build
    external: true
  strava-stats_storage:
    name: strava-stats_storage
    external: true
  strava-stats_logs:
    name: strava-stats_logs
    external: true

logging:
  driver: "json-file"
  options:
    max-size: "20m"
    max-file: "1"
x-dockge:
  urls:
    - https://bike.samskeyti.net/
