services:
  spoolman:
    image: ghcr.io/donkie/spoolman:latest
    container_name: spoolman
    restart: unless-stopped
    ports:
      - "7912:8000"
    env_file: .env
    volumes:
      - ./spoolman/data/:/home/app/.local/share/spoolman/:rw
  
  timelapse:
    image: jrottenberg/ffmpeg:7.1-alpine
    container_name: timelapse
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: >
      apk add --no-cache inotify-tools &&
      while true; do
        sleep 3600;
      done
    env_file: .env
    volumes:
      - frames_smb:/data/incoming/:ro
      - rendered_nfs:/data/rendered/:rw
      - ./timelapse/state/:/state/:rw
    security_opt:
      - no-new-privileges:true

volumes:
  frames_smb:
    driver: local
    driver_opts:
      type: cifs
      o: "addr=172.16.10.170,credentials=/root/.creds/samba,vers=3.0,ro,file_mode=0444,dir_mode=0555"
      device: "//172.16.10.170/data/printer_data/frames"
  rendered_nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.20.42,rw,noatime,nfsvers=4,soft"
      device: ":/tank/printing/timelapse/rendered/"
