immich.samskeyti.net {
    import common
    reverse_proxy http://192.168.30.101:2283
}

plexm.samskeyti.net {
    import common
    reverse_proxy https://192.168.30.203:32400 {
        transport http {
            tls_insecure_skip_verify
        }
    }
}

plexv.samskeyti.net {
    import common
    reverse_proxy https://192.168.30.204:32400 {
        transport http {
            tls_insecure_skip_verify
        }
    }
}
