id.samskeyti.net {
    import common
    reverse_proxy http://192.168.30.100:1411 {
        header_up Host {host}
        header_up X-Forwarded-Proto {scheme}
        header_up X-Forwarded-Host {host}
        header_up X-Forwarded-For {remote}
    }
}

stacks.samskeyti.net {
    import common
    reverse_proxy http://192.168.30.100:5002 {
			import websockets
		}
}

agh.samskeyti.net {
    reverse_proxy http://192.168.30.100:3000
}
