# round-robin subdomain
pve.samskeyti.net {
    import proxmox.agg

    reverse_proxy {
        import proxmox.lb
        import proxmox.proxy
    }
}

# proxmox VE subdomains (node-specific)
kex.samskeyti.net {
    import proxmox.agg

    #reverse_proxy https://192.168.10.42:8006 https://192.168.20.42:8006 {
    reverse_proxy https://192.168.20.42:8006 {
        import proxmox.proxy
    }
}

cerulean.samskeyti.net {
    import proxmox.agg

    reverse_proxy https://192.168.20.43:8006 {
        import proxmox.proxy
    }
}

kvistur.samskeyti.net {
    import proxmox.agg

    reverse_proxy https://192.168.20.44:8006 {
        import proxmox.proxy
    }
}

# proxmox backup server
pbs.samskeyti.net, hoppipolla.samskeyti.net {
	import proxmox.agg

	reverse_proxy https://192.168.30.115:8007 {
		import proxmox.proxy
	}
}
