qaxe.samskeyti.net {
	import common
	reverse_proxy http://172.16.10.167:80
}

gamma1.samskeyti.net {
	import common
	reverse_proxy http://172.16.0.249:80
}

gamma2.samskeyti.net {
	import common
	reverse_proxy http://172.16.0.185:80
}

antminer1.samskeyti.net {
	import common
	reverse_proxy http://192.168.60.10:80
}

antminer2.samskeyti.net {
	import common
	reverse_proxy http://192.168.60.20:80
}
