qaxe.samskeyti.net {
	import common
	reverse_proxy http://172.16.10.167:80
}

#btc.samskeyti.net {
#	import common
#	reverse_proxy http://192.168.30.112:8332
#}

# bch.samskeyti.net {
# 	import common
# 	reverse_proxy http://192.168.30.113:3333
# }
