# immich
immich.samskeyti.net {
    import common
    reverse_proxy http://192.168.30.101:2283
}

# immich-selfie-timelapse
selfie.samskeyti.net {
    import common
    reverse_proxy http://192.168.30.101:5000
}

# plex (music)
# plexm.samskeyti.net {
#     import common
#     reverse_proxy https://192.168.30.102:32400 {
#         transport http {
#             tls_insecure_skip_verify
#         }
#     }
# }

# tautulli (music)
ttm.samskeyti.net {
    reverse_proxy http://192.168.30.102:8181
}

# plex (video)
# plexv.samskeyti.net {
#     import common
#     reverse_proxy https://192.168.30.101:32400 {
#         transport http {
#             tls_insecure_skip_verify
#         }
#     }
# }

# tautulli (video)
ttv.samskeyti.net {
    reverse_proxy http://192.168.30.101:8181
}
