id.samskeyti.net {
    import common
    reverse_proxy http://192.168.30.100:1411 {
        header_up Host {host}
        header_up X-Forwarded-Proto {scheme}
        header_up X-Forwarded-Host {host}
        header_up X-Forwarded-For {remote}
    }
}

stacks.samskeyti.net {
    import common
    reverse_proxy http://192.168.30.100:5002 {
			import websockets
		}
}

# TODO: round-robin for backup LXCs
agh.samskeyti.net {
    import common
    reverse_proxy http://192.168.30.200:3000
}

gli.samskeyti.net {
    import common
    reverse_proxy http://192.168.10.1:80
}

git.samskeyti.net {
    import common
    route /webhook* {
        reverse_proxy http://192.168.30.103:8080
    }
}
