id.samskeyti.net {
    import common
    reverse_proxy http://192.168.30.100:1411
}

stacks.samskeyti.net {
    import common
    reverse_proxy http://192.168.30.100:5002
}

agh.samskeyti.net {
	import common

    # master node IP
	reverse_proxy http://192.168.30.200:3000
}

# git.samskeyti.net {
#     import common
#     route /webhook* {
#         reverse_proxy http://192.168.30.103:8080
#     }
# }

# flint2 router
gli.samskeyti.net {
    import common
    reverse_proxy http://192.168.10.1:80
}

# gigaplus managed switch
gp.samskeyti.net {
    import common
    reverse_proxy http://192.168.10.2:80
}

# HP managed switch
hp.samskeyti.net {
    import common
    reverse_proxy http://192.168.10.3:80
}

# wake-on-LAN
upsnap.smskeyti.net {
    import common
    reverse_proxy http://192.168.30.103:8090
}
