id.samskeyti.net {
    import common
    reverse_proxy http://192.168.30.100:1411 {
        header_up Host {host}
        header_up X-Forwarded-Proto {scheme}
        header_up X-Forwarded-Host {host}
        header_up X-Forwarded-For {remote}
    }
}

stacks.samskeyti.net {
    import common
    reverse_proxy http://192.168.30.100:5002 {
			import websockets
		}
}

agh.samskeyti.net {
	import common

	reverse_proxy {
		to agh-200 http://192.168.30.200:3000 \
		   agh-201 http://192.168.30.201:3000 \
		   agh-202 http://192.168.30.202:3000

		lb_policy first
		lb_try_duration 10s
		lb_try_interval 250ms
		fail_duration 30s

		transport http {
			dial_timeout 2s
		}

		# expose which upstream handled the request
		header_up X-Upstream-Name {upstream_name}
		header_up X-Upstream-Addr {upstream_host}:{upstream_port}
	}
}

gli.samskeyti.net {
    import common
    reverse_proxy http://192.168.10.1:80
}

git.samskeyti.net {
    import common
    route /webhook* {
        reverse_proxy http://192.168.30.103:8080
    }
}
