# fluidd UI
fluidd.samskeyti.net {
    import common
    reverse_proxy http://172.16.10.170:4408
}

# moonraker API
moonraker.samskeyti.net {
    import common
    reverse_proxy http://172.16.10.170:7125
}

# stock K1C camera feed
k1c.samskeyti.net {
    import common
    reverse_proxy http://172.16.10.170:8080
}

# spoolman
spools.samskeyti.net {
    import common
    reverse_proxy http://192.168.30.104:7912
}
