# fluidd UI
k1c.samskeyti.net {
    import common

    # Put specific camera routes before the general Fluidd route.
    handle /webcam/* {
        reverse_proxy http://172.16.10.170 {
            flush_interval -1

            transport http {
                compression off
            }
        }
    }

    # Everything else goes to Fluidd's own web server.
    handle {
        reverse_proxy http://172.16.10.170:4483
    }
}

# spoolman
spoolman.samskeyti.net {
    import common
    reverse_proxy http://192.168.30.104:7912
}
