# fluidd UI
k1c.samskeyti.net {
    import common

    # stock K1C camera
    handle_path /camera/* {
        reverse_proxy http://172.16.10.170:8080 {
            flush_interval -1
        }
    }

    # Fluidd UI
    handle {
        reverse_proxy http://172.16.10.170:4408
    }
}

# spoolman
spools.samskeyti.net {
    import common
    reverse_proxy http://192.168.30.104:7912
}
