# round-robin subdomain
pve.samskeyti.net {
    import proxmox.agg

    reverse_proxy {
        import proxmox.lb
        import proxmox.proxy
    }
}

# proxmox VE subdomains (node-specific)
kex.samskeyti.net {
    import proxmox.agg

    reverse_proxy https://192.168.20.42:8006 {
        import proxmox.proxy
    }
}

cerulean.samskeyti.net {
    import proxmox.agg

    reverse_proxy https://192.168.20.43:8006 {
        import proxmox.proxy
    }
}

valtari.samskeyti.net {
    import proxmox.agg

    reverse_proxy https://192.168.20.46:8006 {
        import proxmox.proxy
    }
}

# kvistur.samskeyti.net {
#     import proxmox.agg

#     reverse_proxy https://192.168.20.44:8006 {
#         import proxmox.proxy
#     }
# }

# proxmox backup server (VM)
pbs.samskeyti.net {
	import proxmox.agg

	reverse_proxy https://192.168.30.110:8007 {
		import proxmox.proxy
	}
}

# proxmox backup server (remote, IN)
pbs2.samskeyti.net, saeglopur.samskeyti.net {
    import proxmox.agg

    reverse_proxy https://100.100.99.42:8007 {
            import proxmox.proxy
    }
}
