services:
  pocket-id:
    container_name: pocket-id
    image: ghcr.io/pocket-id/pocket-id:latest
    restart: always
    cpus: 1.0
    env_file:
      - .env
      - .secrets
    ports:
      - 1411:1411/tcp
    user: 1000:1000
    volumes:
      - ./data/:/app/data/:rw
    healthcheck:
      test: "curl -f http://localhost:1411/healthz"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    networks:
      - pocket-id-net
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"

networks:
  pocket-id-net:
    name: pocket-id-net

x-dockge:
  urls:
    - https://id.samskeyti.net/
