services:
  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: Dockerfile
    image: caddy:local
    cpus: 1
    ports:
      - 80:80/tcp # HTTP
      - 443:443 # HTTPS
      - 443:443/udp # HTTP/3
    env_file:
      - .env
      - .secrets
    networks:
      - caddy-net
    restart: always
    volumes:
      - ./data/:/data/caddy/:rw
      - ./configs/:/etc/caddy/:rw

  keepalived:
    image: osixia/keepalived:latest
    container_name: keepalived
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    env_file:
      - .env
      - keepalived.env

networks:
  caddy-net:
    name: caddy-net
