services:
  speedtest:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest
    # expose:
    #   - 80
    ports:
      - 9374:80/tcp
    env_file: .env
    environment:
      APP_NAME: Samskeyti Speed Tester
      APP_URL: https://speed.samskeyti.com/
      #ASSET_URL: https://speed.samskeyti.com/
      SPEEDTEST_SCHEDULE: 0 0 * * *
    volumes:
      - speedtest-main_db:/config/:rw
    restart: unless-stopped
    healthcheck:
      test: curl -fSs https://speed.samskeyti.com/api/healthcheck | jq -r .message ||
        exit 1
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
    networks:
      - proxy-net
  # vpntest:
  #   image: lscr.io/linuxserver/speedtest-tracker:latest
  #   container_name: vpntest
  #   network_mode: container:gluetun # use VPN
  #   env_file: .env
  #   environment:
  #     APP_NAME: SSK VPN Speed Tester
  #     APP_URL: https://speed-vpn.samskeyti.com/
  #     #ASSET_URL: https://speed-vpn.samskeyti.com/vpn/
  #     SPEEDTEST_SCHEDULE: 30 */1 * * *
  #   volumes:
  #     - speedtest-vpn_db:/config/:rw
  #   restart: unless-stopped
  #   healthcheck:
  #     test: curl -fSs https://speed-vpn.samskeyti.com/api/healthcheck | jq -r .message || exit 1
  #     interval: 10s
  #     retries: 3
  #     start_period: 30s
  #     timeout: 10s
networks:
  proxy-net:
    external: true

volumes:
  speedtest-main_db:
    name: speedtest-main_db
    external: true
  speedtest-vpn_db:
    name: speedtest-vpn_db
    external: true

x-dockge:
  urls:
    - https://speed.samskeyti.net/
    - https://speed-vpn.samskeyti.net/
