services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    env_file:
      - .env
      - .secrets
    volumes:
      - ./config/:/config/qBittorrent/:rw
      - ./ui/:/ui/:rw
      - qbittorrent-queue_nfs:/work/queue/:rw
      - qbittorrent-active_nfs:/work/downloading/:rw
      - qbittorrent-complete_nfs:/work/complete/:rw
    network_mode: container:gluetun # use VPN
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"

volumes:
  qbittorrent-queue_nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.20.42,nolock,soft,rw,nfsvers=4"
      device: ":/tank/downloads/qbittorrent/00-queued/"
  qbittorrent-active_nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.20.42,nolock,soft,rw,nfsvers=4"
      device: ":/tank/downloads/qbittorrent/01-downloading/"
  qbittorrent-complete_nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.20.42,nolock,soft,rw,nfsvers=4"
      device: ":/tank/downloads/qbittorrent/02-complete/"

x-dockge:
  urls:
    - https://qb.samskeyti.net/
