services:
  pocket-id:
    container_name: pocket-id
    image: ghcr.io/pocket-id/pocket-id:v1
    restart: unless-stopped
    env_file: .env
    ports:
      - 1411:1411/tcp
    volumes:
      - pocket-id_db:/app/data/:rw
    healthcheck:
      test: "curl -f http://localhost:1411/healthz"
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    networks:
      - pocket-id-net


networks:
  pocket-id-net:
    name: pocket-id-net
volumes:
  pocket-id_db:
    name: pocket-id_db
    external: true

logging:
  driver: "json-file"
  options:
    max-size: "20m"
    max-file: "1"
x-dockge:
  urls:
    - https://id.samskeyti.net/
