services:
  plex-music:
    container_name: plex-music
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
    env_file: .env
#    privileged: true
    volumes:
      - plex-music_data:/config/:rw
      - /mnt/hot-pool/backups/virtual-machines/plex-music/:/backups/:rw
      - /mnt/hot-pool/media/audio/:/media/:rw
      - /dev/shm/plex-transcode/:/transcode/:rw
    networks:
      - plex-music-net
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"
  # TODO: add oauth2
  tautulli-music:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    env_file: .env
    volumes:
      - /data/:/plex-data/:ro
      - tautulli-music_data:/config/:rw
#    user: ${PUID}:${PGID}
    ports:
      - 8181:8181/tcp
    restart: unless-stopped
    depends_on:
      - plex-music
    networks:
      - plex-music-net
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"

networks:
  plex-music-net:
    name: plex-music-net

volumes:
  plex-music_data:
    external: true
  tautulli-music_data:
    external: true

x-dockge:
  urls:
    - https://plexm.samskeyti.net/
