services:
  traccar:
    image: traccar/traccar:latest
    container_name: traccar
    restart: unless-stopped
    env_file: .env
#    expose:
#      - 8082
#      - 5002
    ports:
      - 8082:8082/tcp # UI
      - 5002:5002 # service
    volumes:
      - traccar_logs:/opt/traccar/logs/:rw
      - traccar_db:/opt/traccar/data/:rw
      - /self-hosted/traccar/config/:/opt/traccar/conf/:rw
    networks:
      - proxy-net
networks:
  proxy-net:
    external: true
volumes:
  traccar_logs:
    name: traccar_logs
    external: true
  traccar_db:
    name: traccar_db
    external: true
x-dockge:
  urls:
    - https://traccar.samskeyti.net/
