services:
  spoolman:
    image: ghcr.io/donkie/spoolman:latest
    container_name: spoolman
    restart: unless-stopped
    ports:
      - 7912:8000/tcp
    env_file: .env
    volumes:
      - ./data/:/home/app/.local/share/spoolman:rw
    networks:
      - spoolman-net

networks:
  spoolman-net:
    name: spoolman-net
