# TODO: update for split Plex servers
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    env_file: .env
    volumes:
      - /self-hosted/plex/plexmediaserver/Logs/:/plex-logs/:ro
      - /self-hosted/plex/tautulli/config/:/config/:rw
    user: ${PUID}:${PGID}
    ports:
      - 8181:8181/tcp
    restart: unless-stopped
    depends_on:
      - plex
    networks:
      - tautulli-net
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"

networks:
  tautulli-net:
    name: tautulli-net

x-dockge:
  urls:
    - https://tautulli.samskeyti.net/
