services:
  plex-video:
    container_name: plex-video
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
    env_file: .env
    volumes:
      - /mnt/data/plex-video/appdata/:/config/:rw
      - /mnt/ephemeral/backups/:/backups/:rw
      - data_nfs:/media/:rw
      - /dev/shm/plex-transcode/:/transcode/:rw
    runtime: nvidia
    networks:
      - plex-video-net
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"
  # TODO: add oauth2
  tautulli-video:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    env_file: .env
    volumes:
      - /mnt/data/plex-video/appdata/:/plex-data/:ro
      - tautulli-video_data:/config/:rw
    ports:
      - 8181:8181/tcp
    restart: unless-stopped
    depends_on:
      - plex-video
    networks:
      - plex-video-net
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"


networks:
  plex-video-net:
    name: plex-video-net

volumes:
  plex-video_data:
    external: true
  tautulli-video_data:
    external: true
  data_nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.20.42,rw,nfsvers=4.2"
      device: ":/srv/mergerfs/cold_pool/media/videos/plex/"
x-dockge:
  urls:
    - https://plexv.samskeyti.net/
