# base site config - compression and tls (no security headers)
(common) {
        # restrict access to lan and vpn ranges only
        #@denied not client_ip private_ranges 192.168.20.0/24 10.10.10.0/24 100.100.0.0/16
        #abort @denied

        # enable compression
        encode zstd gzip

        # tls configuration for dns challenge and resolver
        tls {
		dns cloudflare {env.CLOUDFLARE_API_TOKEN}
                resolvers 1.1.1.1:53
                propagation_timeout 10m
        }
}

# optional security headers (import alongside common if needed)
(security) {
        header {
                x-real-ip {http.request.remote}
                strict-transport-security "max-age=31536000; includeSubdomains"
                x-content-type-options nosniff
                x-frame-options DENY
                referrer-policy no-referrer-when-downgrade
        }
}
