# reusable snippet for websocket/reverse proxy headers
websockets {
    header_up Host {http.request.host}
    header_up X-Real-IP {http.request.remote.host}
    header_up Connection {>Connection}
    header_up Upgrade {>Upgrade}
}
