name: immich
services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yaml
      service: nvenc
    runtime: nvidia
    # cpus: 8
    user: 1000:1000
    volumes:
      - data_nfs:/data/:rw
      - photography_nfs:/external/photography/:rw
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
      - .secrets
    ports:
      - 2283:2283/tcp
    depends_on:
      immich-db:
        condition: service_healthy
        restart: true
      immich-redis:
        condition: service_healthy
        restart: true
    restart: always
    healthcheck:
      disable: false
    networks:
      - immich-net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
  immich-ml:
    container_name: immich-ml
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends:
      file: hwaccel.ml.yaml
      service: cuda
    runtime: nvidia
    # cpus: 8
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /mnt/ephemeral/model-cache/:/cache/:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
    env_file:
      - .env
      - .secrets
    restart: always
    healthcheck:
      disable: false
    networks:
      - immich-net
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
  immich-redis:
    container_name: immich-redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    cpus: 1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich-net
    env_file:
      - .env
      - .secrets
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
  immich-db:
    container_name: immich-db
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    cpus: 1
    env_file:
      - .env
      - .secrets
    volumes:
      - ./data/immich/:/var/lib/postgresql/data/:rw
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      # start_interval: 30s
      start_period: 5m
    command:
      - postgres
      - -c
      - shared_preload_libraries=vectors.so
      - -c
      - search_path="$$user", public, vectors
      - -c
      - logging_collector=on
      - -c
      - max_wal_size=2GB
      - -c
      - shared_buffers=512MB
      - -c
      - wal_compression=on

    restart: always
    networks:
      - immich-net

  immich-selfie-timelapse:
    container_name: immich-selfie-timelapse
    image: arnaudcayrol/immich-selfie-timelapse:latest
    restart: always
    env_file:
      - .env
      - .secrets
    ports:
      - 5000:5000/tcp
    networks:
      - immich-net
    volumes:
      - ./data/selfie-timelapse/config/:/app/config:rw
      - selfies_nfs:/app/output:rw

networks:
  immich-net:
    name: immich-net

volumes:
  data_nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.20.42,hard,rw,noatime,nfsvers=4"
      device: ":/tank/media/photos/immich/"
  photography_nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.20.42,hard,rw,noatime,nfsvers=4"
      device: ":/tank/media/photos/photography/"
  selfies_nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.20.42,hard,rw,noatime,nfsvers=4"
      device: ":/tank/media/photos/related/immich-selfie-timelapse/"

x-dockge:
  urls:
    - https://immich.samskeyti.net/
