services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    env_file: .env
    volumes:
      - qbittorrent_config:/config/qBittorrent/:rw
      - qbittorrent_ui:/ui/:rw
      - /mnt/mega-pool/downloads/qbittorrent/:/hdd/:rw
    network_mode: container:gluetun # use VPN
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
logging:
  driver: "json-file"
  options:
    max-size: "20m"
    max-file: "1"
x-dockge:
  urls:
    - https://qb.samskeyti.net/
volumes:
  qbittorrent_config:
    name: qbittorrent_config
    external: true
  qbittorrent_ui:
    name: qbittorrent_ui
    external: true
networks:
  proxy-net:
    external: true
