services:
  soulseek:
    image: slskd/slskd:latest
    container_name: soulseek
    env_file: .env
    user: 1000:1000
    volumes:
      - ./db/:/app/data/:rw
      - ./slskd.yml:/app/slskd.yml:rw
      - soulseek_nfs:/app/:rw
    restart: unless-stopped
    network_mode: container:gluetun # use VPN
    # depends_on:
    #   gluetun:
    #     condition: service_healthy
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"

volumes:
  soulseek_nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.20.42,hard,rw,nfsvers=4"
      device: ":/tank/downloads/soulseek/"

x-dockge:
  urls:
    - https://soulseek.samskeyti.net/
