services:
  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: Dockerfile
    cpus: 1.0
    ports:
      - 80:80/tcp # HTTP
      - 443:443 # HTTPS
      - 443:443/udp # HTTP/3
    env_file: .env
    networks:
      - caddy-net
    restart: always
    dns: 192.168.30.100
    volumes:
      - caddy_data:/data/caddy/:rw
      - ./configs/:/etc/caddy/:rw
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"
networks:
  caddy-net:
    name: caddy-net
volumes:
  caddy_data:
    external: true
