services:
  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80/tcp # HTTP
      - 443:443 # HTTPS
      - 443:443/udp # HTTP/3
    env_file: .env
    #network_mode: host
    networks:
      - caddy-net
    restart: always
    volumes:
      - caddy_data:/data/caddy/:rw
      - ./configs/:/etc/caddy/:rw
networks:
  caddy-net:
    name: caddy-net
volumes:
  caddy_data:
    external: true
