services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: always
    cpus: 1
    volumes:
      - work:/opt/adguardhome/work/:rw
      - ./configs/:/opt/adguardhome/conf/:rw
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"

# named volumes
volumes:
  work: {}
