services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: always
    cpus: 1
    volumes:
      - work:/opt/adguardhome/work/:rw
      - ./configs/:/opt/adguardhome/conf/:rw
    network_mode: host

# named volumes
volumes:
  work: {}
