services:
  plex-video:
    container_name: plex-video
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    runtime: "nvidia"
    ports:
      - 32400:32400/tcp
    env_file: .env
    volumes:
      - ./data/plex/:/config/:rw
      - backups_nfs:/backups/:rw
      - videos_nfs:/media/videos/:rw
      - /dev/shm/plex-transcode/:/transcode/:rw
    networks:
      - plex-video-net
  # TODO: add oauth2
  tautulli-video:
    container_name: tautulli
    image: lscr.io/linuxserver/tautulli:latest
    cpus: 1
    env_file: .env
    volumes:
      - ./data/plex/:/plex-data/:ro
      - ./data/tautulli/:/config/:rw
    ports:
      - 8181:8181/tcp
    restart: unless-stopped
    depends_on:
      - plex-video
    networks:
      - plex-video-net

networks:
  plex-video-net:
    name: plex-video-net

volumes:
  videos_nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.20.42,soft,rw,noatime,nfsvers=4"
      device: ":/tank/media/videos/plex/"
  backups_nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.20.42,hard,rw,noatime,nfsvers=4"
      device: ":/tank/backups/apps/plex-video/"

x-dockge:
  urls:
    - https://plexv.samskeyti.net/
