services:
  plex-video:
    container_name: plex-video
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
    env_file: .env
    volumes:
      - ./data/:/config/:rw
      - ./backups:/backups/:rw
      - /media/:/media/:rw
      - /dev/shm/plex-transcode/:/transcode/:rw
    networks:
      - plex-video-net
networks:
  plex-video-net:
    name: plex-video-net
x-dockge:
  urls:
    - https://plexv.samskeyti.net/
