include:
  - qbittorrent/compose.yaml
  - soulseek/compose.yaml

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 0.0.0.0:8090:8090       # qbittorrent web UI
      - 0.0.0.0:5030:5030/tcp   # soulseek web UI
      - 0.0.0.0:50300:50300/tcp # soulseek service port
      - 0.0.0.0:9823:9823/tcp   # VPN speedtest port
    env_file:
      - .env
      - .secrets
    volumes:
      - ./data/:/gluetun/:rw
    networks:
      - gluetun-net
    security_opt:
      - no-new-privileges:true
    restart: always
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 2m
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"

  # qbittorrent-oauth:
  #   container_name: qbittorrent-oauth
  #   image: quay.io/oauth2-proxy/oauth2-proxy:latest
  #   command: --config /oauth2-proxy.cfg
  #   restart: always
  #   expose:
  #     - 8091
  #   env_file: .env
  #   volumes:
  #     - ./oauth2/qb-oauth2-proxy.cfg:/oauth2-proxy.cfg:ro
  #   networks:
  #     - gluetun-net
  #   depends_on:
  #     - gluetun
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "20m"
  #       max-file: "1"

  # soulseek-oauth:
  #   container_name: soulseek-oauth
  #   image: quay.io/oauth2-proxy/oauth2-proxy:latest
  #   command: --config /oauth2-proxy.cfg
  #   restart: always
  #   expose:
  #     - 5031
  #   env_file: .env
  #   volumes:
  #     - ./oauth2/ss-oauth2-proxy.cfg:/oauth2-proxy.cfg:ro
  #   networks:
  #     - gluetun-net
  #   depends_on:
  #     - gluetun
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "20m"
  #       max-file: "1"

networks:
  gluetun-net:
    name: gluetun-net
