# deprecated in favor of bare metal installation
services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    hostname: Starálfur
    env_file: .env
    volumes:
      - syncthing_db:/var/syncthing/config/:rw
      - ${HDD_POOL}/app-data/syncthing/sync/:/data/sync/:rw
      - ${WG_MESH}:/data/
      #network_mode: host
    networks:
      - proxy-net
    ports:
      - 22000:22000
      - 8384:8384/tcp
    restart: unless-stopped
    cap_add:
      - CAP_CHOWN
      - CAP_FOWNER
    user: ${PUID}:${PGID}
networks:
  proxy-net:
    external: true
volumes:
  syncthing_db:
    name: syncthing_db
    external: true
x-dockge:
  urls:
    - https://sync.samskeyti.net/
