name: Docker Apps Deploy

on:
  push:
    branches: [main]

jobs:
  update-lxc:
    runs-on: github-runner-lxc
    steps:
      - uses: actions/checkout@v4
      - run: bash .github/scripts/update-lxc.sh

  deploy-app:
    needs: update-lxc
    runs-on: github-runner-lxc
    steps:
      - uses: actions/checkout@v4
      - run: bash .github/scripts/docker-deploy.sh
