services:
  dockge-app:
    container_name: dockge
    image: louislam/dockge:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - dockge_db:/app/data/:rw
      - /self-hosted/:/opt/stacks/:rw
    env_file: .env
    networks:
      - dockge-net
#    extra_hosts:
#      - smaskifa:192.168.42.44
#      - schnitzel:10.10.10.7
#      - kex-docker-cpu:192.168.20.101
#      - kex-docker-gpu:192.168.20.109
  dockge-oauth:
    container_name: dockge-oauth
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    command: --config /oauth2-proxy.cfg
    restart: always
    # expose:
    #   - 5001
    ports:
      - 5001:5001/tcp
    env_file: .env
    volumes:
      - /self-hosted/dockge/oauth2-proxy.cfg:/oauth2-proxy.cfg:ro
    networks:
      - dockge-net
      - proxy-net
    depends_on:
      - dockge-app
networks:
  dockge-net:
    name: dockge-net
  proxy-net:
    external: true
volumes:
  dockge_db:
    name: dockge_db
    external: true
x-dockge:
  urls:
    - https://stacks.samskeyti.net/
