services:
  tabby:
    image: ghcr.io/tabbyml/tabby-rocm:latest
    container_name: tabby
    command: >
      serve
      --device rocm
      --chat-model qwen3-coder-next:q4_K_M
      --completion-model qwen3-coder-next:q4_K_M
    ports:
      - "8080:8080/tcp"
    volumes:
      - /models/:/data/:rw
      - ./config:/root/.tabby/:rw
    devices:
      - /dev/kfd
      - /dev/dri
    env_file: .env
    restart: unless-stopped

volumes:
  data:
