services:
  tabby:
    # image: ghcr.io/tabbyml/tabby-rocm:latest
    build:
      context: ./source
      dockerfile: docker/Dockerfile.rocm
    image: tabby-rocm:local
    container_name: tabby
    command: >
      serve
      --device rocm
#      --model qwen3-coder-next:q4_K_M
    ports:
      - 8080:8080/tcp
    volumes:
      - ./config/:/data/:rw
      - /models/:/models/:rw
    devices:
      - /dev/kfd
      - /dev/dri
    env_file: .env
    restart: unless-stopped
