services:
  tabby:
    image: ghcr.io/tabbyml/tabby-rocm:latest
    container_name: tabby-rocm
    command: >
      serve
      --model Qwen2.5-Coder-14B
      --device rocm
    ports:
      - "8080:8080/tcp"
    volumes:
      - data:/data
    devices:
      - /dev/kfd
      - /dev/dri
    env_file: .env
    restart: unless-stopped

volumes:
  data:
